"use client";

import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/app/AuthProvider";
import { useState, useEffect } from "react";
import LogoOutline from "@/components/shared/LogoOutline";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });

  useEffect(() => {
    const handleMouseMove = (event: MouseEvent) => {
      setMousePosition({ x: event.clientX, y: event.clientY });
    };

    window.addEventListener("mousemove", handleMouseMove);

    return () => {
      window.removeEventListener("mousemove", handleMouseMove);
    };
  }, []);

  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-white`}
        >
          {/* Logo Outline */}
          <LogoOutline />

          {/* Animated orange accent */}
          <div
            className="fixed w-64 h-64 rounded-full bg-orange-500 blur-3xl z-10"
            style={{
              left: mousePosition.x - 128,
              top: mousePosition.y - 128,
              transition: "all 0.5s ease-out",
              opacity: 0.15, // Slightly reduced opacity
            }}
          />

          {/* Main content */}
          <div className="relative z-20 min-h-screen flex flex-col">
            {children}
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
